runfile('C:/Users/bjraiv23/Documents/GitHub/Python-Experiment-Control-Code/DataAcquisition.py', wdir='C:/Users/bjraiv23/Documents/GitHub/Python-Experiment-Control-Code')
Reloaded modules: WolframMathematicaAnalysisFunctions
session started
[-0.01549259 -0.01629718 -0.01742361 ... -0.01533167 -0.0182282
 -0.01710177]
()
[]
session started
[]
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
session started
[-0.01871095 -0.01838912 -0.01887187 ... -0.01613626 -0.01871095
 -0.01694085]
()
[]
session started
[]
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
session started
[-0.01726269 -0.01774544 -0.01903279 ... -0.01581443 -0.01661902
 -0.01790636]
()
[]
session started
[]
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
session started
[-0.01710177 -0.01629718 -0.01903279 ... -0.01758453 -0.01517076
 -0.01855003]
()
[]
session started
[]
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
If the number of argument to Fit is fewer than 3, the first argument should be a list {designMatrix, response}.
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
(Fit[(), (1, Global`x, Power[Global`x, 2], Power[Global`x, 3], Power[Global`x, 4])],)
session started
[-0.01694085 -0.01774544 -0.01806728 ... -0.01871095 -0.01677994
 -0.01452708]
Socket exception: Socket operation aborted.
Failed to start.
Traceback (most recent call last):

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\kernelcontroller.py", line 435, in _kernel_start
    response = self.kernel_socket_in.recv_abortable(

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\zmqsocket.py", line 50, in recv_abortable
    raise SocketAborted("Socket operation aborted.")

SocketAborted: Socket operation aborted.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\bjraiv23\Documents\GitHub\Python-Experiment-Control-Code\DataAcquisition.py", line 128, in <module>
    take_data(10, 100000)

  File "C:\Users\bjraiv23\Documents\GitHub\Python-Experiment-Control-Code\DataAcquisition.py", line 35, in take_data
    analysis(data)

  File "C:\Users\bjraiv23\Documents\GitHub\Python-Experiment-Control-Code\DataAcquisition.py", line 87, in analysis
    peaks = wlc.fabry_perot_get_peaks(fp_signal, 80, 1)

  File "C:\Users\bjraiv23\Documents\GitHub\Python-Experiment-Control-Code\WolframMathematicaAnalysisFunctions.py", line 24, in fabry_perot_get_peaks
    peaks = session.evaluate(wl.FindPeaks(fp_array, smoothing, 0, threshold))

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 259, in evaluate
    result = self.evaluate_wrap(expr, **kwargs)

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 256, in evaluate_wrap
    return self.evaluate_wrap_future(expr, **kwargs).result()

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 252, in evaluate_wrap_future
    self.ensure_started()

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 203, in ensure_started
    self.start(block=True, timeout=None)

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 157, in start
    raise e

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\localsession.py", line 152, in start
    future.result(timeout=timeout)

  File "C:\Users\bjraiv23\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()

  File "C:\Users\bjraiv23\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\kernelcontroller.py", line 527, in run
    self._safe_kernel_start()

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\kernelcontroller.py", line 366, in _safe_kernel_start
    raise e

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\kernelcontroller.py", line 360, in _safe_kernel_start
    self._kernel_start()

  File "C:\Users\bjraiv23\Anaconda3\lib\site-packages\wolframclient\evaluation\kernel\kernelcontroller.py", line 455, in _kernel_start
    raise WolframKernelException(

WolframKernelException: Failed to communicate with kernel: C:\Program Files\Wolfram Research\Mathematica\12.2\WolframKernel.exe.

